_wandb:
    value:
        cli_version: 0.21.4
        e:
            40so5snqv5apyh0odphht2zfe3mvyjvb:
                args:
                    - --num_of_classes
                    - "94"
                    - --epochs
                    - "50"
                    - --batch_size
                    - "256"
                    - --lr
                    - "3e-4"
                    - --downstream_dataset
                    - NFM
                    - --datasets_dir
                    - /mnt/disk1/aiotlab/namth/EEGFoundationModel/datasets/nfm_eegpt_official
                    - --foundation_dir
                    - /mnt/disk1/aiotlab/namth/EEGFoundationModel/EEGPT/checkpoint/official.ckpt
                codePath: finetune_main.py
                codePathLocal: finetune_main.py
                email: nam.th180805@gmail.com
                executable: /mnt/disk1/aiotlab/envs/hoainiemeegpt/bin/python
                git:
                    commit: a0e0a8fad729e2ecf4eedb3a81548a6e6d48a705
                    remote: https://github.com/BINE022/EEGPT.git
                host: gpus-Super-Server
                os: Linux-6.8.0-65-generic-x86_64-with-glibc2.35
                program: /mnt/disk1/aiotlab/namth/EEGFoundationModel/EEGPT/finetune_main.py
                python: CPython 3.11.13
                root: /mnt/disk1/aiotlab/namth/EEGFoundationModel/EEGPT
                startedAt: "2025-09-22T15:11:29.484962Z"
                writerId: 40so5snqv5apyh0odphht2zfe3mvyjvb
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 51
                - 53
                - 63
                - 71
                - 103
            "3":
                - 13
                - 16
            "4": 3.11.13
            "5": 0.21.4
            "6": 4.35.2
            "12": 0.21.4
            "13": linux-x86_64
batch_size:
    value: 256
classifier:
    value: all_patch_reps
clip_value:
    value: 1
cuda:
    value: 0
datasets_dir:
    value: /mnt/disk1/aiotlab/namth/EEGFoundationModel/datasets/nfm_eegpt_official
downstream_dataset:
    value: NFM
dropout:
    value: 0.1
epochs:
    value: 50
foundation_dir:
    value: /mnt/disk1/aiotlab/namth/EEGFoundationModel/EEGPT/checkpoint/official.ckpt
frozen:
    value: false
label_smoothing:
    value: 0.1
lr:
    value: 0.0003
model_dir:
    value: ./data/wjq/models_weights/Big/BigFaced
multi_lr:
    value: false
num_of_classes:
    value: 94
num_workers:
    value: 16
optimizer:
    value: AdamW
project_name:
    value: ""
seed:
    value: 3407
use_pretrained_weights:
    value: true
weight_decay:
    value: 0.05
